### PR TITLE
Wall avoidance system

### LINKED ISSUE #11: Wall avoidance

### PR DESCRIPTION
**Pull request by a5huynh**
Closes #11. Based a bit on #67.

- [x] Added a `ClosestObstacleSystem` which adds any close walls as a `Closest<Obstacle>` component on a creature
- [x] Added a `SeekSystem::<Obstacle>` that treats obstacle like a predator so the creature avoids it.

### CODE REVIEW

**Review by marotili — APPROVED** [review]
LGTM and we can merge this if you want, but maybe you want to explore something first:
With your change the entities will run away from the wall, but can we also do it so that they move along the wall?

**Comment by a5huynh** [comment]
@marot Yeah that's no problem! Would this be related to the changes you made in your PR to the `SeekSystem` to take in Rotation vectors? I can play around w/ that to get try and get that wall effect.

**Comment by marotili** [comment]
@a5huynh Yep that was my intention, but maybe another (more explicit) approach might fit better. Not sure about it.

**Comment by a5huynh** [comment]
@marot I adjusted your idea a bit w/ a rotation + magnitude. It seems to work, the creatures follow the wall now rather then run away (albeit they all take the same rotation away from the wall now).

Let me know if that works otherwise I can revert that commit!

**Comment by marotili** [comment]
No this looks great. Thank you :)

**Pull request merged**
