### PR TITLE
Cleanup: remove unused attributes component

### PR DESCRIPTION
**Pull request by marotili**
I missed this component while implementing `Fullness`.

### CODE REVIEW

**Comment by marotili** [comment]
@khskarl Is it okay if we split creature attributes into separate components or am I missing something?

**Comment by khskarl** [comment]
You mean one component per attribute? Won't this lead to a lot of components? 🤔 And what advantages will this bring? 

I'm not opposed to this, I just don't currently hold an opinion on the matter and you seem to have something in mind.

**Comment by marotili** [comment]
I have no production experience so this is mostly based on gut feeling:

Advantages:
- Data dependencies visible in `SystemData`. With one attribute component we would need to check the source code to see where attributes are used.
- No `Option<Attribute>` necessary to indicate that an attribute might not be used, instead the component is not added to the entity.
- More flexible: E.g. switch between different digestion components/systems. I think this is a big win early on in development.

Disadvantages:
- Number of components might be hard to manage (I have seen people request a search function in Unity's component list)
- Harder to see what components are in use / data all over the place
- Maybe there are performance implications

**Comment by khskarl** [comment]
I'm convinced, and I really want to know what it will feel like to develop with many components. Attribute per component, let's do it!

**Comment by erlend-sh** [comment]
☝️ very happy with this quick resolution.

I think we can often afford to just try this kind of thing out for a while instead of deliberating over whether it's the Right Way or not. If someone more experienced with Amethyst best practices chimes in here we'll either proceed with confidence or revert and call it a successful investigation.

**Pull request merged**
