### PR TITLE
Controls button off the Main Menu

### PR DESCRIPTION
**Pull request by chrispetkau**
Addressing issue #52, Add a shortcut legend to the menu screen stand-alone: https://github.com/amethyst/evoli/issues/52

Added a Controls button to the Main Menu. It displays a list of input actions and their associated hotkeys as defined in the InputHandler resource.

### CODE REVIEW

**Comment by sunreef** [comment]
Very nice. I tested it on Ubuntu and it works nicely.

Some small comments:
 - could you move the controls panel down a bit ? Right now it overlaps with the title of the game that you added.
- I'm not a big fan of the flashy green color you chose. Can you make it more neutral ? Maybe keep the same gray tone we used for the rest of the UI for now ?

**Comment by chrispetkau** [comment]
> * could you move the controls panel down a bit ? Right now it overlaps with the title of the game that you added.

I never saw this in my testing. What resolution are you running at?

**Comment by sunreef** [comment]
The resolution is fixed by the `display_config.ron` file. Right now, it's at 1280x960.

Screenshot from 2019-07-15 15-44-07

That's what it looks like on my side.

**Comment by chrispetkau** [comment]
Huh. 1280x960 on my side after the changes (made overlay grey and moved it down 100 pixels). 
evoli_main_menu

**Comment by sunreef** [comment]
Your picture doesn't look like 1280x960. It looks much larger. What's the resolution of your screen ?

The title takes a lot more space in the window on my side.

Screenshot from 2019-07-15 16-34-46

**Comment by chrispetkau** [comment]
Mystery solved. My screen is at 3200x1800 but i had a Scaling feature set to 200%. I dialed the scaling back down to 100% and I get the same results as you.
I moved the title up a bit and it looks good now.

**Pull request merged**
