### PR TITLE
- Removed PausedState and implemented pause directly in main_game.rs.

### PR DESCRIPTION
**Pull request by chrispetkau**
This allows the user to interact with the game while it is paused,
which is desirable.
- Correctly initialize and reset time scale changes in on_start and
on_stop respectively so that exiting and re-entering MainGameState
maintains program integrity.
- Restored deletion of all organisms in MainGameState::on_stop(). This
important line was deleted when it was last integrated.
- Changed text color of ui buttons to have higher contrast.

### CODE REVIEW

**Comment by erlend-sh** [comment]
Thanks! Do you have an account on our chat or forum? We’d like to be able to stay in touch with you outside of GH issues.

**Comment by sunreef** [comment]
I agree that the paused state has become irrelevant now that we have a menu state that acts in a similar way. The pause button should only control the time scale like the slow down and speed up buttons do.

In the long term, we would need to separate between the Start menu state and the Pause menu state (similar to what you get when pressing Escape in most games). 

In PR #92, I made it so that going to the menu state from the game state pushes a new state on the state machine and going back to the game pops that state. This way, `on_start` is only called the first time you get to the main game. I had more in mind the Escape menu when I did this. Maybe I should create a distinct state for this.

In any case, thanks for these changes :)

**Comment by chrispetkau** [comment]
> Thanks! Do you have an account on our chat or forum? We’d like to be able to stay in touch with you outside of GH issues.

I am Str4ngeL00p on Discord and I lurk around the Amethyst Discord most days.

**Comment by erlend-sh** [comment]
Nothing is coming up when I search for it. Please add to friends or DM erlend_sh#4477 on there.

**Pull request merged**
