### PR TITLE
Issue #50, add  Menu button to in-game UI.

### PR DESCRIPTION
**Pull request by chrispetkau**
Looking into augmenting the in-game menu to support going back to the main menu, I refactored time_control.rs to improve my understanding and improve maintainability.
- centralize strings to avoid spelling mistakes across duplications
- factor out methods (translate_click(), handle_action()) to reduce indentation and singularize responsibilities
- cache look-up results and re-use them rather than looking them up on every run()

### CODE REVIEW

**Comment by chrispetkau** [comment]
Went ahead and implemented issue #50. Put a prefab in for the main game ui and replaced the specific time_control.rs with a more generic main_game_ui.rs. Added CreatureTag component which is added to every entity created by the creature spawner system; all such entities are deleted when we transition from the MainGameState back to the MenuState.

**Comment by chrispetkau** [comment]
Hm. I will stop editing the same comment and just append new ones. This PR is ready to go. Transitions between MainGameState and MenuState properly terminate and restart the MainGameState.

**Comment by chrispetkau** [comment]
One known issue: If the main game is paused, the Menu button won't return you to the main menu.

**Comment by erlend-sh** [comment]
Thanks a bunch! @khskarl will have time for code review this weekend.

**Pull request merged**
