### PR TITLE
Add a basic implementation of the Topplegrass creature

### PR DESCRIPTION
**Pull request by Jazarro**
Refer to issue #61
Topplegrass is explained here: https://community.amethyst.rs/t/evoli-creature-designs/814/10

Any entity with the Movement component intelligently avoids obstacles. However, not all entities that can move can steer; for example, Topplegrass is moved only by the wind. Therefore, add a new component tag AvoidObstaclesTag to all entities that are supposed to steer.

Add new resource Wind. Implement debug keyboard inputs to change wind direction and speed. Load initial wind vector from a config file. In order to load from file, pass the assets directory path to the loading state.

Add gravity system that affects entities with the FallingTag.

Add system that deletes Topplegrass entities when they leave the world bounds.

### CODE REVIEW

**Comment by erlend-sh** [comment]
Thanks so much for this, gonna be fun to add another creature in the game!

Do you have any way to test on MacOS by any chance? Two of us with Mac have been unable to run it. This issue might very well predate your PR though, as we can’t run latest master either. As @khskarl said:

> A shader is failing to compile and (maybe by consequence) there is a memory leak.

If you happen to be able to help with this we can get this merged faster, as the rest of the maintainers are on hiatus at the moment.

**Comment by Jazarro** [comment]
I'm afraid I'll not be much use there, as I've never touched a mac in my life. :)

**Comment by erlend-sh** [comment]
Gotcha. In that case please hang tight as we wait for a developer with a Mac and some attention to spare. :)

**Comment by Jazarro** [comment]
Force pushed to rebase back onto master.

**Pull request merged**
